# NumPy Exercises with Hints

To a some extent, this collection is based on exercises from <https://github.com/rougier/numpy-100> which have been selected by ZI UZH & David Pinezich for the ZI APPD course. The exercises 3-9 have been adapted and their numbering no longer is consistent with the online ressource.

A few hints on how to proceed with the exercises: 
* Use IPython's `?` operator to read documentation on the functions, e.g. `np.any?`
* Try to come up with a naive solution first, and only think about a better solution after, i.e. if you can use any NumPy functions or structs to simplify your code. For example, it's not wrong to try to iterate through an array and change every element in a first version (and yes, there probably is an easier way to do it with NumPy functions)
* Feel free to always ask questions if you're stuck
* Using pen and paper to come up with a solution idea is helpful in a lot of situations
* [google.com](http://www.google.com) and [stackoverflow.com](http://www.stackoverflow.com) are your best buddies while programming


#### 1. Import the numpy package under the name `np` (★☆☆) 


In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
np.show_config

2.3.3


<function numpy.show_config(mode='stdout')>

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\]) 

In [5]:
a = np.zeros((10))
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [6]:
a = np.random.randint(0, 30, (3, 3, 3))
print(a)

[[[ 0  9 13]
  [17 13  0]
  [16 24 20]]

 [[ 4 17 22]
  [23 19  7]
  [23  6 23]]

 [[28 13  7]
  [15 12 25]
  [ 4  5  9]]]


#### 5.  How to get information on the dimensions of an array (★☆☆) 
(**hint**: ndim, shape)

In [10]:
Z = np.random.random((10,10))
print(Z)
print(Z.ndim)
print(Z.shape)

[[0.70109742 0.31377375 0.76963404 0.36985829 0.40408447 0.76269409
  0.47655811 0.51650511 0.47404592 0.3017721 ]
 [0.74025439 0.38202942 0.54569294 0.3047286  0.0890689  0.54571507
  0.57910191 0.1578323  0.41339192 0.64315083]
 [0.58008075 0.78651146 0.87028491 0.02303807 0.38683977 0.74613911
  0.27797456 0.94866135 0.27393616 0.88143707]
 [0.32932653 0.76306285 0.13997553 0.04514827 0.17175768 0.69805536
  0.5390365  0.02986333 0.34064867 0.80760577]
 [0.0897716  0.60220855 0.00368026 0.57386782 0.00138074 0.31542288
  0.43618205 0.67331147 0.97522481 0.49124252]
 [0.94591113 0.377247   0.74116324 0.58649918 0.23975172 0.66745496
  0.84480612 0.22157283 0.30057133 0.09770542]
 [0.4284994  0.42041667 0.97525002 0.80263117 0.41147252 0.62588488
  0.96654843 0.29438805 0.98575588 0.52051034]
 [0.16033926 0.54281864 0.88392978 0.44510168 0.66857923 0.89068084
  0.55933346 0.66487111 0.3419575  0.34952797]
 [0.3625452  0.77073809 0.64391493 0.6672794  0.94912258 0.17576417
  0.22406381

#### 6.  Return only the even numbers in a 1D array (★☆☆) 
(**hint**: Use slicing)

In [13]:
Z = np.arange(50)
E = Z[::2]
print(Z)
print(E)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


#### 7. Create a 10x10 array with 1 on the border and 0 inside (★☆☆) 
(**hint**: Use slicing)

In [6]:
X=np.ones((10,10))
X[1:9,1:9] = 0
X

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 8. Find the maximum value in a random 5x5 array and calculate for all elements the percentages to the maximum value (★☆☆) 
(**hint**: max, use ufuncs)

In [18]:
A = np.random.randint(0, 30, (5, 5))
m = A.max()
D = A / m
print(A)
print(m)
print(D)

[[27  7  0  5 26]
 [14  0 16  3  2]
 [15 27 28  0 22]
 [ 5 24 15 25  9]
 [16  8 13 13  2]]
28
[[0.96428571 0.25       0.         0.17857143 0.92857143]
 [0.5        0.         0.57142857 0.10714286 0.07142857]
 [0.53571429 0.96428571 1.         0.         0.78571429]
 [0.17857143 0.85714286 0.53571429 0.89285714 0.32142857]
 [0.57142857 0.28571429 0.46428571 0.46428571 0.07142857]]


#### 9. With the help of Boolean masking, extract from the array `np.array([3,4,6,10,24,89,45,43,46,99,100])` the numbers (★☆☆) 

* which are not divisible by 3
* which are divisible by 5
* which are divisible by 3 and 5
* which are divisible by 3 and set them to 42

(**hint**: Use the modulo operator)


In [21]:
O = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])
BM_Ndiv3 = (O % 3 != 0)
BM_div5 = (O % 5 == 0)
BM_div35 = (O % 3 == 0) & (O % 5 == 0)
BM_div3 = (O % 3 == 0)
print(O[BM_Ndiv3])
print(O[BM_div5])
print(O[BM_div35])
O[BM_div3] = 42
print(O)

[  4  10  89  43  46 100]
[ 10  45 100]
[45]
[ 42   4  42  10  42  89  42  43  46  42 100]


## Bonus exercises, a bit more difficult and just for fun.

Selected examples from <https://github.com/rougier/numpy-100>.


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [4]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

#### 39. Create an array with values ranging from 0 to 1 and elements inbetween which are spaced 0.1 (★★☆) 
(**hint**: np.linspace)

#### 40. Create a random array of size 10 and sort it (★★☆) 
(**hint**: sort)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

#### 50. How to find the closest value (to a given scalar) in a vector to another given value? (★★☆)

(**hint**: argmin)

In [4]:
Z = np.arange(100)
v = np.random.uniform(0,100)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [4]:
X = np.random.rand(5, 10)

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [4]:
Z = np.random.randint(0,10,(3,3))

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [4]:
Z = np.random.randint(0,3,(3,10))

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [4]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)